### ISSUE TITLE
Export Summary fails when test contains a "survey" question

### ISSUE THREAD

**Issue by austin48** [sakaicontrib/mneme-project#10]
- Create an new Assessment
- Add a question
- Set the question to True / False
- Check "Click to make this a survey question"
- Continue creating the question and test
- Publish the assessment
- Take the test
- Click grading
- Select the test
- Click "Export of Data"

The export fails with

2016-10-06 16:22:45,506  WARN ajp-bio-8009-exec-164 org.etudes.mneme.impl.AttachmentServiceImpl - summary spreadsheet: 
java.lang.NullPointerException

**Comment by buckett** [comment]
There is a PR out for this in: #11

**Comment by buckett** [comment]
To reproduce this I had to add another question that has some points assigned to it otherwise the assessment is invalid and can't be taken. The full stack trace is:
```
app_1  | java.lang.NullPointerException
app_1  | 	at org.etudes.mneme.impl.AttachmentServiceImpl.createResponsesSheet(AttachmentServiceImpl.java:4003)
app_1  | 	at org.etudes.mneme.impl.AttachmentServiceImpl.handleAccessDownload(AttachmentServiceImpl.java:2094)
app_1  | 	at org.etudes.mneme.impl.AttachmentServiceImpl$1.handleAccess(AttachmentServiceImpl.java:749)
app_1  | 	at org.sakaiproject.access.tool.AccessServlet.dispatch(AccessServlet.java:348)
app_1  | 	at org.sakaiproject.access.tool.AccessServlet.doGet(AccessServlet.java:194)
app_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
app_1  | 	at org.sakaiproject.vm.ComponentServlet.service(ComponentServlet.java:56)
app_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
app_1  | 	at org.sakaiproject.oauth.filter.OAuthPostFilter.doFilter(OAuthPostFilter.java:75)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
app_1  | 	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:460)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
app_1  | 	at org.sakaiproject.oauth.filter.OAuthPreFilter.doFilter(OAuthPreFilter.java:74)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
app_1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
app_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
app_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
app_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
app_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
app_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
app_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
app_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
app_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
app_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
app_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
app_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
app_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
app_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
app_1  | 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by buckett** [comment]
Should be fixed now, thanks @austin48
