### ISSUE TITLE
Mic tool doesn't work as a student.

### ISSUE THREAD

**Issue by buckett** [sakaicontrib/mneme-project#4]
Reported by Austin that the mic tool in CKEditor doesn't work if you're a student.

**Comment by buckett** [comment]
Fixed.

**Comment by buckett** [comment]
I am still having problems with the mic tool in CKEditor, but it looks to be a frontend JS issue. I did see this stack trace when testing:
```
app_1  | org.sakaiproject.exception.IdUnusedException id: /private/mneme/84f46035-f0c4-41d6-8ea3-ae966b1882a8/docs/
app_1  | 	at org.sakaiproject.site.impl.BaseSiteService.getDefinedSite(BaseSiteService.java:675)
app_1  | 	at org.sakaiproject.site.impl.BaseSiteService.getSite(BaseSiteService.java:753)
app_1  | 	at org.sakaiproject.connector.fck.FCKConnectorServlet.bypassAddAttachment(FCKConnectorServlet.java:1123)
app_1  | 	at org.sakaiproject.connector.fck.FCKConnectorServlet.doPost(FCKConnectorServlet.java:488)
app_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
app_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
app_1  | 	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:460)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
app_1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
app_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
app_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
app_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
app_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
app_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
app_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
app_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
app_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
app_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
app_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
app_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
app_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
app_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
app_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
app_1  | 	at java.lang.Thread.run(Thread.java:748)
```
